[[plugins]]
repo = 'Shougo/dein.vim'

#colorscheme start
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'herrbischoff/cobalt2.vim'

[[plugins]]
repo = 'nightsense/stellarized'

[[plugins]]
repo = 'nightsense/nemo'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
# colorscheme end

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

#linting and formatting
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# git(display changes)
[[plugins]]
repo = 'tpope/vim-fugitive'

# display match count
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'deoplete-plugins/deoplete-tag'

[[plugins]]
repo = 'haya14busa/vim-asterisk'

[[plugins]]
repo = 'junegunn/fzf'
build = 'bash ./install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'lilydjwg/colorizer'
hook_add = '''
    let g:colorizer_maxlines = 500
	let g:colorizer_nomap = 1
'''

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    let g:lsp_async_completion = 1
    let g:lsp_diagnostics_enabled = 1
    let g:lsp_signs_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:lsp_virtual_text_enabled = 0
    let g:lsp_highlights_enabled = 0
    let g:lsp_textprop_enabled = 1
    let g:lsp_signs_error = {'text': 'x'}
    let g:lsp_signs_warning = {'text': '!'}
    nnoremap <Space>ld :LspDefinition<CR>
    nnoremap <Space>lf :LspDocumentFormat<CR>
    nnoremap <Space>lh :LspHover<CR>
    nnoremap <Space>lr :LspReferences<CR>

    if executable('clangd')
        autocmd User lsp_setup call lsp#register_server({
            \ 'name': 'clangd',
            \ 'cmd': {server_info->['clangd', '-background-index']},
            \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cmake'],
        \ })
        autocmd FileType c,cpp,objc,objcpp,cmake setlocal omnifunc=lsp#complete
    endif
    if executable('pyls')
        autocmd User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
        \ })
        autocmd FileType python setlocal omnifunc=lsp#complete
    endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"
    imap <C-Space> <Plug>(asyncomplete_force_refresh)
    let g:asyncomplete_auto_popup = 1
    autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-neosnippet.vim'
hook_add = '''
    autocmd User lsp_setup call asyncomplete#register_source(asyncomplete#sources#neosnippet#get_source_options({
        \ 'name': 'neosnippet',
        \ 'whitelist': ['*'],
        \ 'completor': function('asyncomplete#sources#neosnippet#completor'),
    \ }))
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
'''
