[[plugins]]
repo = 'Shougo/dein.vim'

#color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

#linting and formatting
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# git(display changes)
[[plugins]]
repo = 'tpope/vim-fugitive'

# git(various commands)
[[plugins]]
repo = 'airblade/vim-gitgutter'

# display match count
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'tyru/restart.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'lazywei/vim-matlab'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
