[[plugins]]
repo = 'Shougo/dein.vim'

#colorscheme start
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'herrbischoff/cobalt2.vim'

[[plugins]]
repo = 'nightsense/stellarized'

[[plugins]]
repo = 'nightsense/nemo'

[[plugins]]
repo = 'ayu-theme/ayu-vim'
# colorscheme end

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

#linting and formatting
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# git(display changes)
[[plugins]]
repo = 'tpope/vim-fugitive'

# display match count
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'deoplete-plugins/deoplete-tag'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
